#!/usr/bin/env python3
r"""Rebuild every derived artefact from the frozen run. No GPU, no network.

Reads  : runs/exp_baseline/2025_original/summary.csv   (frozen probe output)
         runs/exp_baseline/2025_original/trials.json    (raw run, for the count check)
Writes : runs/exp_baseline/2025_original/metrics.json
         runs/exp_baseline/2025_original/derived/table{2,3,4,5}.tex   (reference
             fragments -- the paper's tables are hand-written inline; these let
             you diff the numbers, they are not \input by the paper)
         paper/figs/fig1_flow.png, paper/figs/fig2_matched.png,
         paper/figs/fig4_confusion.png, paper/figs/fig5_verif.png     (regenerated
             from paper/figs/src/*.py; byte-identical unless the generators changed)

To rebuild summary.csv itself (re-run the probe over trials.json):
    python scripts/rescore_baseline.py     # needs code/probe_input.py + code/layer_4_oracle.py

Usage:  python scripts/regen_all.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (BASELINE_RUN, ROOT, compute_metrics, load_trials,
                    read_summary)

DERIVED = BASELINE_RUN / "derived"


def _f(x: float) -> str:
    return f"{x:.2f}"


def table2(m) -> str:
    o = m["table_overall"]
    lines = [
        r"% Table 2 (tab:overall) -- regenerated by scripts/regen_all.py",
        r"\begin{tabular}{@{}l @{\hspace{1.8em}} S[table-format=2.0] @{\hspace{1.6em}} S @{\hspace{1.6em}} S @{\hspace{1.6em}} S @{}}",
        r"\toprule",
        r"\textbf{Class} & {\textbf{n}} & {\textbf{Precision}} & {\textbf{Recall}} & {\textbf{F1}} \\",
        r"\midrule",
    ]
    for c in ("clean", "world_drift", "halluc"):
        r = o[c]
        lines.append(fr"\textsf{{{c.replace('_', r'\_')}}} & {r['n']} & "
                     fr"{_f(r['P'])} & {_f(r['R'])} & {_f(r['F1'])} \\")
    lines += [r"\bottomrule", r"\end{tabular}",
              fr"% overall accuracy {_f(o['accuracy'])} ({o['n_correct']} of {o['n']})"]
    return "\n".join(lines) + "\n"


def table3(m) -> str:
    conf = m["confusion"]
    out = [r"% Table 3 (tab:conf) confusion matrix -- rows gold, cols pred",
           r"%                 clean  world_drift  halluc"]
    for g in ("clean", "world_drift", "halluc"):
        row = conf[g]
        out.append(f"% {g:14s} {row['clean']:5d} {row['world_drift']:11d} {row['halluc']:6d}")
    return "\n".join(out) + "\n"


def table4(m) -> str:
    out = [r"% Table 4 (tab:baselines) -- recovery of the visible tool-side drifts"]
    for k, v in m["table_baselines"].items():
        out.append(f"% {k:20s} {v[0]} / {v[1]}")
    return "\n".join(out) + "\n"


def table5(m) -> str:
    tv = m["table_verified"]
    out = [r"% Table 5 (tab:verified) -- design-time vs post-hoc verified labels",
           r"% label set            n   acc   drift_F1  belief"]
    for key, lab in [("design_all", "design-time, all"),
                     ("design_vis", "design-time, visible"),
                     ("verified_all", "verified, all"),
                     ("verified_vis", "verified, visible")]:
        d = tv[key]
        out.append(f"% {lab:20s} {d['n']:3d}  {_f(d['acc'])}  {_f(d['drift_f1'])}"
                   f"     {d['belief'][0]}/{d['belief'][1]}")
    return "\n".join(out) + "\n"


def regen_figures() -> list[str]:
    src = ROOT / "paper" / "figs" / "src"
    for gen, out in [("fig1_gen.py", "../fig1_flow.png"),
                     ("fig2_gen.py", "../fig2_matched.png")]:
        subprocess.run([sys.executable, gen, out], cwd=src, check=True,
                       stdout=subprocess.DEVNULL)
    subprocess.run([sys.executable, "crop_fig4_fig5.py"], cwd=src, check=True,
                   stdout=subprocess.DEVNULL)
    return ["paper/figs/fig1_flow.png", "paper/figs/fig2_matched.png",
            "paper/figs/fig4_confusion.png", "paper/figs/fig5_verif.png"]


def main() -> None:
    rows = read_summary()
    n_trials = len(load_trials())
    assert len(rows) == n_trials == 30, (len(rows), n_trials)

    m = compute_metrics(rows)
    (BASELINE_RUN / "metrics.json").write_text(
        json.dumps(m, indent=2) + "\n", encoding="utf-8")

    DERIVED.mkdir(exist_ok=True)
    (DERIVED / "table2.tex").write_text(table2(m), encoding="utf-8")
    (DERIVED / "table3.tex").write_text(table3(m), encoding="utf-8")
    (DERIVED / "table4.tex").write_text(table4(m), encoding="utf-8")
    (DERIVED / "table5.tex").write_text(table5(m), encoding="utf-8")

    figs = regen_figures()

    print("regenerated:")
    for p in ["runs/exp_baseline/2025_original/metrics.json",
              "runs/exp_baseline/2025_original/derived/table2.tex",
              "runs/exp_baseline/2025_original/derived/table3.tex",
              "runs/exp_baseline/2025_original/derived/table4.tex",
              "runs/exp_baseline/2025_original/derived/table5.tex", *figs]:
        print("  ", p)

    cf, vs, bs = m["confusion"], m["visible_split"], m["belief_side"]
    print("\nnumbers baked into fig4_confusion.png (no generator -- eyeball these):")
    print(f"   confusion:  clean [{cf['clean']['clean']},{cf['clean']['world_drift']},{cf['clean']['halluc']}]"
          f"  world_drift [{cf['world_drift']['clean']},{cf['world_drift']['world_drift']},{cf['world_drift']['halluc']}]"
          f"  halluc [{cf['halluc']['clean']},{cf['halluc']['world_drift']},{cf['halluc']['halluc']}]")
    print(f"   drift split: {vs['n_visible_drift']} visible / {vs['n_invisible_drift']} invisible;"
          f" visible-drift recall {vs['caught_visible_drift']}/{vs['n_visible_drift']}")
    print("numbers baked into fig5_verif.png:")
    print(f"   halluc-designed: {bs['n_relabelled_clean']} no belief error, "
          f"{bs['n_ambiguous']} ambiguous, {bs['n_genuine_halluc']} genuine "
          f"(caught {bs['caught_genuine_halluc']}/{bs['n_genuine_halluc']})")


if __name__ == "__main__":
    main()
